{{- if .Values.namespace.create }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "airia-infrastructure-validation.namespace" . }}
  labels:
    {{- include "airia-infrastructure-validation.labels" . | nindent 4 }}
    name: {{ include "airia-infrastructure-validation.namespace" . }}
    purpose: infrastructure-testing
{{- end }}